/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.Paciente;
import Clases.conectar;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.ComboBox;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author dani_
 */
public class AgregarPacienteR extends javax.swing.JFrame {
//conexion
        Paciente p = new Paciente();
        boolean estFec = false;
        boolean estDer=false;
    /**
     * Creates new form AgregarPacienteR
     */
    public AgregarPacienteR() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Agregar Paciente");
        cmbMedico.setModel(p.obtenerDoctor());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNExpediente = new javax.swing.JTextField();
        txtSNombre = new javax.swing.JTextField();
        txtPNombre = new javax.swing.JTextField();
        txtApeMat = new javax.swing.JTextField();
        txtApePat = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        txtCodigoPostal = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDomicilio = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtTelDom = new javax.swing.JTextField();
        txtTelOfi = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtDerechohabiente = new javax.swing.JTextField();
        txtRFC = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtLugarNac1 = new javax.swing.JTextField();
        txtFechaNac = new javax.swing.JTextField();
        txtEstadoCivil = new javax.swing.JTextField();
        cmbSexo = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        cmbMedico = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        btnAgregar = new javax.swing.JButton();
        lblPacientes = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtNombrePadre = new javax.swing.JTextField();
        txtNombreMadre = new javax.swing.JTextField();
        txtNombrePareja = new javax.swing.JTextField();
        txtProcedencia = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtOcupacion = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtEscolaridad = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaObservaciones = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Paciente");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Expediente No.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 970, 10));

        jLabel2.setText("* Nombre(s)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        jLabel3.setText("* Apellidos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jLabel4.setText("* Domicilio");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jLabel5.setText("* Ciudad");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        jLabel6.setText("* Estado");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        jLabel7.setText("* Codigo Postal");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        txtNExpediente.setEditable(false);
        getContentPane().add(txtNExpediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 110, -1));

        txtSNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSNombreKeyReleased(evt);
            }
        });
        getContentPane().add(txtSNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 120, -1));

        txtPNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPNombreKeyReleased(evt);
            }
        });
        getContentPane().add(txtPNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 110, -1));

        txtApeMat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApeMatKeyReleased(evt);
            }
        });
        getContentPane().add(txtApeMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 120, -1));

        txtApePat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApePatKeyReleased(evt);
            }
        });
        getContentPane().add(txtApePat, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 110, -1));

        txtCiudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCiudadKeyReleased(evt);
            }
        });
        getContentPane().add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 240, -1));

        txtCodigoPostal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoPostalKeyReleased(evt);
            }
        });
        getContentPane().add(txtCodigoPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 120, -1));

        txtEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEstadoKeyReleased(evt);
            }
        });
        getContentPane().add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 240, -1));

        txtDomicilio.setColumns(20);
        txtDomicilio.setRows(5);
        txtDomicilio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDomicilioKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txtDomicilio);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 240, 68));

        jLabel8.setText("* Teléfono Dom");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        jLabel9.setText("* Telefono Oficina");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, -1));

        jLabel10.setText("Correo electronico");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, -1, -1));

        jLabel11.setText("* Sexo");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, -1, -1));

        jLabel12.setText("Derechohabiente");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));

        jLabel13.setText("* Fecha de Nacimiento");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, -1, -1));

        jLabel14.setText("* Edad");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, -1, -1));

        jLabel15.setText("* Medico");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, -1, -1));

        txtTelDom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelDomKeyReleased(evt);
            }
        });
        getContentPane().add(txtTelDom, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 159, -1));

        txtTelOfi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelOfiKeyReleased(evt);
            }
        });
        getContentPane().add(txtTelOfi, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 159, -1));

        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCorreoKeyReleased(evt);
            }
        });
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 160, -1));

        jLabel23.setText("* Lugar de Nacimiento");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, -1));

        txtDerechohabiente.setForeground(new java.awt.Color(204, 204, 204));
        txtDerechohabiente.setText("ISSSTE, IMSS, ETC");
        txtDerechohabiente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDerechohabienteKeyReleased(evt);
            }
        });
        getContentPane().add(txtDerechohabiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 158, -1));

        txtRFC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRFCKeyReleased(evt);
            }
        });
        getContentPane().add(txtRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 158, -1));

        txtEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEdadKeyReleased(evt);
            }
        });
        getContentPane().add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 75, -1));

        txtLugarNac1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLugarNac1KeyReleased(evt);
            }
        });
        getContentPane().add(txtLugarNac1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 158, -1));

        txtFechaNac.setForeground(new java.awt.Color(204, 204, 204));
        txtFechaNac.setText("aaaa-mm-dd");
        txtFechaNac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFechaNacKeyReleased(evt);
            }
        });
        getContentPane().add(txtFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 158, -1));

        txtEstadoCivil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEstadoCivilKeyReleased(evt);
            }
        });
        getContentPane().add(txtEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 240, -1));

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opcion", "HOMBRE", "MUJER" }));
        getContentPane().add(cmbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 160, -1));

        jLabel24.setText("RFC");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, -1, -1));

        getContentPane().add(cmbMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 170, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, 14, 300));

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar_paciente.png"))); // NOI18N
        btnAgregar.setText("jButton1");
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, 240, 290));

        lblPacientes.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        lblPacientes.setForeground(new java.awt.Color(255, 255, 255));
        lblPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Paciente.png"))); // NOI18N
        lblPacientes.setText("Agregar Paciente");
        getContentPane().add(lblPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel17.setText("Procedencia");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, -1, -1));

        jLabel18.setText("Ocupacion");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, -1, -1));

        jLabel19.setText("Nombre de la Madre");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        jLabel20.setText("Nombre del Padre");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, -1, -1));

        jLabel21.setText("Nombre de Pareja");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu Azul.png"))); // NOI18N
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        txtNombrePadre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombrePadreKeyReleased(evt);
            }
        });
        getContentPane().add(txtNombrePadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 240, -1));

        txtNombreMadre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreMadreKeyReleased(evt);
            }
        });
        getContentPane().add(txtNombreMadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 240, -1));

        txtNombrePareja.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreParejaKeyReleased(evt);
            }
        });
        getContentPane().add(txtNombrePareja, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 240, -1));

        txtProcedencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProcedenciaKeyReleased(evt);
            }
        });
        getContentPane().add(txtProcedencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, 240, -1));

        jLabel25.setText("Estado Civil");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, -1));

        txtOcupacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOcupacionKeyReleased(evt);
            }
        });
        getContentPane().add(txtOcupacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, 230, -1));

        jLabel26.setText("Escolaridad");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, -1, -1));

        txtEscolaridad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEscolaridadKeyReleased(evt);
            }
        });
        getContentPane().add(txtEscolaridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, 230, -1));

        jLabel27.setText("Observaciones");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, -1, -1));

        txtaObservaciones.setColumns(20);
        txtaObservaciones.setRows(5);
        txtaObservaciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtaObservacionesKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(txtaObservaciones);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 490, 230, 80));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_blanco.jpg"))); // NOI18N
        jLabel16.setText("jLabel16");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 100, 1050, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
      /* if(validarCampos(primer_nom,ape_pat,domicilio, ciudad,estado,Tel_Dom,
               sexo,Lug_Nac,Fec_Nac,2,medico)==true){
           showMessageDialog(null, "se puede insertar");
       }else{
           showMessageDialog(null, "no se puede insertar");
       }
       }
       catch(java.lang.NumberFormatException ex){
           showMessageDialog(null, "Ingrese Edad ");
       }*/      
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        try{
        String nombre = txtPNombre.getText();
        String segundo_nombre = txtSNombre.getText();
        String apellido_paterno = txtApePat.getText();
        String apellido_materno = txtApeMat.getText();
        String domicilio = txtDomicilio.getText();
        String ciudad = txtCiudad.getText();
        String estado = txtEstado.getText();
        String codigo_postal = txtCodigoPostal.getText();
        String tel_domicilio = txtTelDom.getText();
        String tel_oficina = txtTelOfi.getText();
        String correo_electronico = txtCorreo.getText();
        String sexo = cmbSexo.getSelectedItem().toString();
        String derechohabiente = txtDerechohabiente.getText();
        String lugar_nacimiento = txtLugarNac1.getText();
        String fecha_nacimiento = txtFechaNac.getText();
        String edad = txtEdad.getText();
        String rfc = txtRFC.getText();
        String estado_civil = txtEstadoCivil.getText();
        String nombre_madre = txtNombreMadre.getText();
        String nombre_padre = txtNombrePadre.getText();
        String nombre_pareja = txtNombrePareja.getText();
        String procedencia = txtProcedencia.getText();
        String ocupacion = txtOcupacion.getText();
        String escolaridad = txtEscolaridad.getText();
        String observaciones = txtaObservaciones.getText();
        String doctor = cmbMedico.getSelectedItem().toString();
        if(p.validarCampos(nombre, apellido_paterno, domicilio, ciudad, estado, 
                tel_domicilio, tel_oficina, cmbSexo.getSelectedIndex(), lugar_nacimiento, 
                fecha_nacimiento, edad, cmbMedico.getSelectedIndex())){
            if(p.insertarP(nombre, segundo_nombre, apellido_paterno, apellido_materno, 
           domicilio, ciudad, estado, codigo_postal, tel_domicilio, tel_oficina, 
           correo_electronico, sexo, derechohabiente, lugar_nacimiento, 
           fecha_nacimiento, edad, rfc, estado_civil, nombre_madre, nombre_padre, 
           nombre_pareja, procedencia, ocupacion, escolaridad, observaciones, doctor)){
            dispose();
            }
           
        }//insertarP
        }//if validarCampos
        catch(NumberFormatException e){showMessageDialog(null, e.getMessage());}
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void txtPNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPNombreKeyReleased
        txtPNombre.setText(txtPNombre.getText().toUpperCase());
    }//GEN-LAST:event_txtPNombreKeyReleased

    private void txtSNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSNombreKeyReleased
        txtSNombre.setText(txtSNombre.getText().toUpperCase());
    }//GEN-LAST:event_txtSNombreKeyReleased

    private void txtApePatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApePatKeyReleased
        txtApePat.setText(txtApePat.getText().toUpperCase());
    }//GEN-LAST:event_txtApePatKeyReleased

    private void txtApeMatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApeMatKeyReleased
        txtApeMat.setText(txtApeMat.getText().toUpperCase());
    }//GEN-LAST:event_txtApeMatKeyReleased

    private void txtDomicilioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDomicilioKeyReleased
        txtDomicilio.setText(txtDomicilio.getText().toUpperCase());
    }//GEN-LAST:event_txtDomicilioKeyReleased

    private void txtCiudadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCiudadKeyReleased
        txtCiudad.setText(txtCiudad.getText().toUpperCase());
    }//GEN-LAST:event_txtCiudadKeyReleased

    private void txtEstadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstadoKeyReleased
        txtEstado.setText(txtEstado.getText().toUpperCase());
    }//GEN-LAST:event_txtEstadoKeyReleased

    private void txtCodigoPostalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoPostalKeyReleased
        p.soloNumeros(evt);
    }//GEN-LAST:event_txtCodigoPostalKeyReleased

    private void txtTelDomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelDomKeyReleased
        p.validarTelefono(evt);
    }//GEN-LAST:event_txtTelDomKeyReleased

    private void txtEstadoCivilKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstadoCivilKeyReleased
        txtEstadoCivil.setText(txtEstadoCivil.getText().toUpperCase());
    }//GEN-LAST:event_txtEstadoCivilKeyReleased

    private void txtNombreMadreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreMadreKeyReleased
        txtNombreMadre.setText(txtNombreMadre.getText().toUpperCase());
    }//GEN-LAST:event_txtNombreMadreKeyReleased

    private void txtNombrePadreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombrePadreKeyReleased
        txtNombrePadre.setText(txtNombrePadre.getText().toUpperCase());
    }//GEN-LAST:event_txtNombrePadreKeyReleased

    private void txtNombreParejaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreParejaKeyReleased
        txtNombrePareja.setText(txtNombrePareja.getText().toUpperCase());
    }//GEN-LAST:event_txtNombreParejaKeyReleased

    private void txtProcedenciaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProcedenciaKeyReleased
        txtProcedencia.setText(txtProcedencia.getText().toUpperCase());
    }//GEN-LAST:event_txtProcedenciaKeyReleased

    private void txtTelOfiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelOfiKeyReleased
        txtTelOfi.setText(txtTelOfi.getText().toUpperCase());
    }//GEN-LAST:event_txtTelOfiKeyReleased

    private void txtCorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyReleased
        txtCorreo.setText(txtCorreo.getText().toUpperCase());
    }//GEN-LAST:event_txtCorreoKeyReleased

    private void txtDerechohabienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDerechohabienteKeyReleased
        if(estDer==false){
            estDer=true;
            txtDerechohabiente.setForeground(Color.black);
            txtDerechohabiente.setText(evt.getKeyChar()+"");
        }
        txtDerechohabiente.setText(txtDerechohabiente.getText().toUpperCase());
    }//GEN-LAST:event_txtDerechohabienteKeyReleased

    private void txtLugarNac1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLugarNac1KeyReleased
        txtLugarNac1.setText(txtLugarNac1.getText().toUpperCase());
    }//GEN-LAST:event_txtLugarNac1KeyReleased

    private void txtFechaNacKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaNacKeyReleased
        if(estFec==false){
            estFec=true;
            txtFechaNac.setForeground(Color.black);
            txtFechaNac.setText(evt.getKeyChar()+"");
        }
        txtFechaNac.setText(txtFechaNac.getText().toUpperCase());
    }//GEN-LAST:event_txtFechaNacKeyReleased

    private void txtEdadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyReleased
        p.soloNumeros(evt);
    }//GEN-LAST:event_txtEdadKeyReleased

    private void txtRFCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRFCKeyReleased
        txtRFC.setText(txtRFC.getText().toUpperCase());
    }//GEN-LAST:event_txtRFCKeyReleased

    private void txtOcupacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOcupacionKeyReleased
        txtOcupacion.setText(txtOcupacion.getText().toUpperCase());
    }//GEN-LAST:event_txtOcupacionKeyReleased

    private void txtEscolaridadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEscolaridadKeyReleased
        txtEscolaridad.setText(txtEscolaridad.getText().toUpperCase());
    }//GEN-LAST:event_txtEscolaridadKeyReleased

    private void txtaObservacionesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaObservacionesKeyReleased
        txtaObservaciones.setText(txtaObservaciones.getText().toUpperCase());
    }//GEN-LAST:event_txtaObservacionesKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarPacienteR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarPacienteR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarPacienteR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarPacienteR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarPacienteR().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox cmbMedico;
    private javax.swing.JComboBox cmbSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblPacientes;
    private javax.swing.JTextField txtApeMat;
    private javax.swing.JTextField txtApePat;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtCodigoPostal;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDerechohabiente;
    private javax.swing.JTextArea txtDomicilio;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEscolaridad;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtEstadoCivil;
    private javax.swing.JTextField txtFechaNac;
    private javax.swing.JTextField txtLugarNac1;
    private javax.swing.JTextField txtNExpediente;
    private javax.swing.JTextField txtNombreMadre;
    private javax.swing.JTextField txtNombrePadre;
    private javax.swing.JTextField txtNombrePareja;
    private javax.swing.JTextField txtOcupacion;
    private javax.swing.JTextField txtPNombre;
    private javax.swing.JTextField txtProcedencia;
    private javax.swing.JTextField txtRFC;
    private javax.swing.JTextField txtSNombre;
    private javax.swing.JTextField txtTelDom;
    private javax.swing.JTextField txtTelOfi;
    private javax.swing.JTextArea txtaObservaciones;
    // End of variables declaration//GEN-END:variables
}//clase
