/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author Carlos Puga
 */
public class Expediente extends javax.swing.JFrame {

    /**
     * Creates new form Expediente
     */
    public Expediente() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("EXPEDIENTE");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        lblNuevaConsulta = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNExpediente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTelOfi = new javax.swing.JTextField();
        txtPNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtApePat = new javax.swing.JTextField();
        txtSNombre = new javax.swing.JTextField();
        txtApeMat = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cmbSexo = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDomicilio = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        txtDerechohabiente = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtLugarNac1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtRFC = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCodigoPostal = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTelDom = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cmbMedico = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        txtFechaNac = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        txtEstadoCivil = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtNombreMadre = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtNombrePadre = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtNombrePareja = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtProcedencia = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtOcupacion = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtEscolaridad = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        txtAreaPatologicos = new javax.swing.JScrollPane();
        jTextArea23 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        txtAreaNoPAtologicos = new javax.swing.JScrollPane();
        jTextArea24 = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        rdbtnParto = new javax.swing.JRadioButton();
        rdbtnCesarea = new javax.swing.JRadioButton();
        spnEdadGestacional = new javax.swing.JSpinner();
        spnNoGestacion = new javax.swing.JSpinner();
        txtSitioParto = new javax.swing.JTextField();
        txtTalla = new javax.swing.JTextField();
        txtPesoAlNacer = new javax.swing.JTextField();
        spnToracico = new javax.swing.JSpinner();
        spnCefalico = new javax.swing.JSpinner();
        spnAbdominal = new javax.swing.JSpinner();
        spnApgar = new javax.swing.JSpinner();
        spnSilverman = new javax.swing.JSpinner();
        spnBallard = new javax.swing.JSpinner();
        txtAnestesia = new javax.swing.JTextField();
        checkIctericia = new javax.swing.JCheckBox();
        checkCianosis = new javax.swing.JCheckBox();
        checkConvulsiones = new javax.swing.JCheckBox();
        checkHemorragias = new javax.swing.JCheckBox();
        checkApnea = new javax.swing.JCheckBox();
        checkAnestesia = new javax.swing.JCheckBox();
        jLabel46 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtAreaComplicaciones = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel47 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel54 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel55 = new javax.swing.JLabel();
        txtFormulaMenstrual = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        txtFUM = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        txtCitologia = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        cmbFrecuencia = new javax.swing.JComboBox<>();
        cmbDuracion = new javax.swing.JComboBox<>();
        cmbCantidad = new javax.swing.JComboBox<>();
        jLabel58 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        spnVidaSexual = new javax.swing.JSpinner();
        jLabel63 = new javax.swing.JLabel();
        spnNoParejas = new javax.swing.JSpinner();
        txtTipo = new javax.swing.JTextField();
        cmbInicio = new javax.swing.JComboBox<>();
        cmbSuspencion = new javax.swing.JComboBox<>();
        jLabel67 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jLabel69 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel70 = new javax.swing.JLabel();
        cmbFPP = new javax.swing.JComboBox<>();
        jLabel72 = new javax.swing.JLabel();
        spnG = new javax.swing.JSpinner();
        spnA = new javax.swing.JSpinner();
        spnP = new javax.swing.JSpinner();
        spnC = new javax.swing.JSpinner();
        spnNacidosVivos = new javax.swing.JSpinner();
        spnNacidosMuertos = new javax.swing.JSpinner();
        spnViven = new javax.swing.JSpinner();
        spnMuertoPrimeraSem = new javax.swing.JSpinner();
        spnMuertoDesPrimeraSem = new javax.swing.JSpinner();
        jLabel81 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jLabel82 = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        jLabel83 = new javax.swing.JLabel();
        txtMediacionGestional = new javax.swing.JTextField();
        jLabel84 = new javax.swing.JLabel();
        txtExamenesComplementarios = new javax.swing.JTextField();
        jLabel85 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jLabel86 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtAreaAbdomen = new javax.swing.JTextArea();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel89 = new javax.swing.JLabel();
        txtAreaCabeza = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jLabel90 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        txtAreaCuello = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jPanel13 = new javax.swing.JPanel();
        jLabel93 = new javax.swing.JLabel();
        txtAreaCuello1 = new javax.swing.JScrollPane();
        txtAreaColumnaVertebral = new javax.swing.JTextArea();
        jLabel94 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel95 = new javax.swing.JLabel();
        txtAreaCuello2 = new javax.swing.JScrollPane();
        txtAreaExploracionGinegologica = new javax.swing.JTextArea();
        jLabel96 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel97 = new javax.swing.JLabel();
        txtAreaCuello3 = new javax.swing.JScrollPane();
        txtAreaExploracionNeurologica = new javax.swing.JTextArea();
        jLabel98 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel99 = new javax.swing.JLabel();
        txtAreaCuello4 = new javax.swing.JScrollPane();
        txtAreaExtremidades = new javax.swing.JTextArea();
        jLabel100 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel101 = new javax.swing.JLabel();
        txtAreaCuello5 = new javax.swing.JScrollPane();
        txtAreaGenitales = new javax.swing.JTextArea();
        jLabel102 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel103 = new javax.swing.JLabel();
        txtAreaCuello6 = new javax.swing.JScrollPane();
        txtAreaHabitusExterior = new javax.swing.JTextArea();
        jLabel104 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel105 = new javax.swing.JLabel();
        txtAreaCuello7 = new javax.swing.JScrollPane();
        txtAreaTorax = new javax.swing.JTextArea();
        jLabel106 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel21 = new javax.swing.JPanel();
        jLabel107 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        txtAreaCardiovascular = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();
        jPanel22 = new javax.swing.JPanel();
        jLabel109 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        txtAreaDigestivo = new javax.swing.JScrollPane();
        jTextArea10 = new javax.swing.JTextArea();
        jPanel23 = new javax.swing.JPanel();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        txtAreaEndocrino = new javax.swing.JScrollPane();
        jTextArea11 = new javax.swing.JTextArea();
        jPanel24 = new javax.swing.JPanel();
        jLabel113 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        txtAreaHemolinfatico = new javax.swing.JScrollPane();
        jTextArea12 = new javax.swing.JTextArea();
        jPanel25 = new javax.swing.JPanel();
        jLabel115 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        txtAreaMusculo = new javax.swing.JScrollPane();
        jTextArea13 = new javax.swing.JTextArea();
        jPanel26 = new javax.swing.JPanel();
        jLabel117 = new javax.swing.JLabel();
        jLabel118 = new javax.swing.JLabel();
        txtAreaPiel = new javax.swing.JScrollPane();
        jTextArea14 = new javax.swing.JTextArea();
        jPanel27 = new javax.swing.JPanel();
        jLabel119 = new javax.swing.JLabel();
        jLabel120 = new javax.swing.JLabel();
        txtAreaReproductor = new javax.swing.JScrollPane();
        jTextArea15 = new javax.swing.JTextArea();
        jPanel28 = new javax.swing.JPanel();
        jLabel121 = new javax.swing.JLabel();
        jLabel122 = new javax.swing.JLabel();
        txtAreaRespiratorio = new javax.swing.JScrollPane();
        jTextArea16 = new javax.swing.JTextArea();
        jPanel29 = new javax.swing.JPanel();
        jLabel123 = new javax.swing.JLabel();
        jLabel124 = new javax.swing.JLabel();
        txtAreaSistemaNervioso = new javax.swing.JScrollPane();
        jTextArea17 = new javax.swing.JTextArea();
        jPanel30 = new javax.swing.JPanel();
        jLabel125 = new javax.swing.JLabel();
        jLabel126 = new javax.swing.JLabel();
        txtAreaSistemasGenerales = new javax.swing.JScrollPane();
        jTextArea18 = new javax.swing.JTextArea();
        jPanel31 = new javax.swing.JPanel();
        jLabel127 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        txtAreaCuello8 = new javax.swing.JScrollPane();
        jTextArea19 = new javax.swing.JTextArea();
        jPanel32 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        txtAreaDiagnostico1 = new javax.swing.JScrollPane();
        txtAreaTratamiento = new javax.swing.JTextArea();
        txtAreaDiagnostico = new javax.swing.JScrollPane();
        jTextArea22 = new javax.swing.JTextArea();
        txtAreaSintomas = new javax.swing.JScrollPane();
        jTextArea20 = new javax.swing.JTextArea();
        jLabel133 = new javax.swing.JLabel();
        jLabel131 = new javax.swing.JLabel();
        jLabel132 = new javax.swing.JLabel();
        jLabel129 = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        txtAreaMotivoConsulta = new javax.swing.JScrollPane();
        jTextArea21 = new javax.swing.JTextArea();
        jLabel134 = new javax.swing.JLabel();
        lblGuardarExpediente = new javax.swing.JLabel();
        lblEliminarExpediente = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Consulta");
        getContentPane().add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 73, -1, 20));

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Expediente");
        getContentPane().add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        lblNuevaConsulta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNuevaConsulta.setForeground(new java.awt.Color(255, 255, 255));
        lblNuevaConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Consulta_32.png"))); // NOI18N
        lblNuevaConsulta.setText("Nueva Consulta");
        lblNuevaConsulta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblNuevaConsulta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblNuevaConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNuevaConsultaMouseClicked(evt);
            }
        });
        getContentPane().add(lblNuevaConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 10, 80));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 10, 80));

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Expediente No.");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        txtNExpediente.setEditable(false);
        txtNExpediente.setText("1");
        jPanel2.add(txtNExpediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 110, -1));

        jLabel9.setText("Telefono Oficina");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));
        jPanel2.add(txtTelOfi, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 159, -1));

        txtPNombre.setText(" ");
        jPanel2.add(txtPNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 110, -1));

        jLabel3.setText("Nombre(s)");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel4.setText("Apellidos");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtApePat.setText(" ");
        jPanel2.add(txtApePat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 110, -1));

        txtSNombre.setText(" ");
        jPanel2.add(txtSNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 120, -1));

        txtApeMat.setText(" ");
        jPanel2.add(txtApeMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 120, -1));

        jLabel10.setText("Correo electronico");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));
        jPanel2.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 160, -1));

        jLabel11.setText("Sexo");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, -1));

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opcion", "Hombre", "Mujer" }));
        jPanel2.add(cmbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 160, -1));

        jLabel5.setText("Domicilio");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        txtDomicilio.setColumns(20);
        txtDomicilio.setRows(5);
        jScrollPane1.setViewportView(txtDomicilio);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 240, 68));

        jLabel12.setText("Derechohabiente");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, -1));
        jPanel2.add(txtDerechohabiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 158, -1));

        jLabel23.setText("Lugar de Nacimiento");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));
        jPanel2.add(txtLugarNac1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 158, -1));

        jLabel13.setText("Fecha de Nacimiento");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));
        jPanel2.add(txtRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 158, -1));

        txtCiudad.setText(" ");
        jPanel2.add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 240, -1));

        jLabel6.setText("Ciudad");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel7.setText("Estado");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        txtEstado.setText(" ");
        jPanel2.add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 240, -1));

        jLabel8.setText("Codigo Postal");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        txtCodigoPostal.setText(" ");
        jPanel2.add(txtCodigoPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 120, -1));

        jLabel14.setText("Teléfono Dom");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));
        jPanel2.add(txtTelDom, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 159, -1));

        jLabel15.setText("Edad");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, -1, -1));
        jPanel2.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 75, -1));

        jLabel16.setText("Medico");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, -1, -1));

        cmbMedico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cmbMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 136, -1));

        jLabel24.setText("RFC");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, -1, -1));
        jPanel2.add(txtFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 158, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 970, 10));

        jLabel25.setText("Estado Civil");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        txtEstadoCivil.setText(" ");
        jPanel2.add(txtEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 240, -1));

        jLabel19.setText("Nombre de la Madre");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, -1, -1));

        txtNombreMadre.setText(" ");
        jPanel2.add(txtNombreMadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 240, -1));

        jLabel20.setText("Nombre del Padre");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        txtNombrePadre.setText(" ");
        jPanel2.add(txtNombrePadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 240, -1));

        jLabel21.setText("Nombre de Pareja");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        txtNombrePareja.setText(" ");
        jPanel2.add(txtNombrePareja, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 240, -1));

        jLabel17.setText("Procedencia");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        txtProcedencia.setText(" ");
        jPanel2.add(txtProcedencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 240, -1));

        jLabel18.setText("Ocupacion");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, -1, -1));
        jPanel2.add(txtOcupacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 230, -1));

        jLabel26.setText("Escolaridad");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, -1, -1));
        jPanel2.add(txtEscolaridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 230, -1));

        jLabel27.setText("Observaciones");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 230, 80));

        jTabbedPane1.addTab("Informacion Personal", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setText("Observaciones:");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"A.V.C", null, null, null, null},
                {"Alergias", null, null, null, null},
                {"Anomalias Congenitas", null, null, null, null},
                {"Cancer", null, null, null, null},
                {"Cardiopatias", null, null, null, null},
                {"Ceguera congénita", null, null, null, null},
                {"Daltonismo", null, null, null, null},
                {"Diabetes", null, null, null, null},
                {"Enf. Mental", null, null, null, null},
                {"Enf. Pulmonar", null, null, null, null},
                {"Entem. Congénitas", null, null, null, null},
                {"Epilepsia", null, null, null, null},
                {"Hipertensión Arterial", null, null, null, null},
                {"Neoplasia", null, null, null, null},
                {"Oncologicos", null, null, null, null},
                {"Sordera", null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ENFERMEDAD", "ABUELOS", "HERMANOS", "MADRE", "PADRE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 460, 230));

        jLabel22.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 480, 460));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane4.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 460, -1));

        jTabbedPane2.addTab("Hereditarios", jPanel1);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setBorder(javax.swing.BorderFactory.createTitledBorder("Antecedentes Patológicos"));
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 530, 460));

        jTextArea23.setColumns(20);
        jTextArea23.setRows(5);
        txtAreaPatologicos.setViewportView(jTextArea23);

        jPanel4.add(txtAreaPatologicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 490, 420));

        jTabbedPane2.addTab("Patológicos", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "No Patologicos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel5.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 500, 500));

        jTextArea24.setColumns(20);
        jTextArea24.setRows(5);
        txtAreaNoPAtologicos.setViewportView(jTextArea24);

        jPanel5.add(txtAreaNoPAtologicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 460, 460));

        jTabbedPane2.addTab("No Patológicos", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setText("Edad gestacional");
        jPanel6.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, 20));

        rdbtnParto.setBackground(new java.awt.Color(255, 255, 255));
        rdbtnParto.setText("Parto");
        jPanel6.add(rdbtnParto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        rdbtnCesarea.setBackground(new java.awt.Color(255, 255, 255));
        rdbtnCesarea.setText("Cesarea");
        jPanel6.add(rdbtnCesarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));
        jPanel6.add(spnEdadGestacional, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 50, -1));
        jPanel6.add(spnNoGestacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 50, -1));
        jPanel6.add(txtSitioParto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 320, -1));
        jPanel6.add(txtTalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 140, -1));
        jPanel6.add(txtPesoAlNacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 140, -1));
        jPanel6.add(spnToracico, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 80, -1));
        jPanel6.add(spnCefalico, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 80, -1));
        jPanel6.add(spnAbdominal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 80, -1));
        jPanel6.add(spnApgar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 80, -1));
        jPanel6.add(spnSilverman, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 80, -1));
        jPanel6.add(spnBallard, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 80, -1));
        jPanel6.add(txtAnestesia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 310, -1));

        checkIctericia.setBackground(new java.awt.Color(255, 255, 255));
        checkIctericia.setText("Ictericia");
        jPanel6.add(checkIctericia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, 20));

        checkCianosis.setBackground(new java.awt.Color(255, 255, 255));
        checkCianosis.setText("Cianosis");
        jPanel6.add(checkCianosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, 20));

        checkConvulsiones.setBackground(new java.awt.Color(255, 255, 255));
        checkConvulsiones.setText("Convulsiones");
        jPanel6.add(checkConvulsiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, -1, 20));

        checkHemorragias.setBackground(new java.awt.Color(255, 255, 255));
        checkHemorragias.setText("Hemorragias");
        jPanel6.add(checkHemorragias, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, 20));

        checkApnea.setBackground(new java.awt.Color(255, 255, 255));
        checkApnea.setText("Apnea Neonatal");
        jPanel6.add(checkApnea, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, 20));

        checkAnestesia.setBackground(new java.awt.Color(255, 255, 255));
        checkAnestesia.setText("Anestesia");
        jPanel6.add(checkAnestesia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, 20));

        jLabel46.setText("Observaciones");
        jPanel6.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        jLabel44.setForeground(new java.awt.Color(102, 102, 102));
        jLabel44.setText("especifique");
        jPanel6.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, 20));

        jLabel45.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel6.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 450, 180));

        jLabel43.setText("Complicaciones:");
        jPanel6.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel42.setText("Ballard");
        jPanel6.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, 20));

        jLabel41.setText("Silverman/And.");
        jPanel6.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, 20));

        jLabel40.setText("Apgar");
        jPanel6.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 20));

        jLabel39.setText("Abdominal");
        jPanel6.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, 20));

        jLabel37.setText("Torácico");
        jPanel6.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, 20));

        jLabel38.setText("Cefálico");
        jPanel6.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 20));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel36.setText("Perimetros (cm)");
        jPanel6.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel34.setText("Talla");
        jPanel6.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, 20));

        jLabel35.setText("Peso al Nacer");
        jPanel6.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, 20));

        jLabel33.setText("Sitio de Atencion del Parto");
        jPanel6.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel30.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PERINATALES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel6.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 490, 500));

        jLabel32.setText("No. de gestación");
        jPanel6.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, 20));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        txtAreaComplicaciones.setViewportView(jTextArea3);

        jPanel6.add(txtAreaComplicaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 450, 50));

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane5.setViewportView(jTextArea4);

        jPanel6.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 430, 90));

        jLabel47.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESUMEN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel6.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 360, 500));

        jTabbedPane2.addTab("Perinatales", jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel52.setText("Menarca");
        jPanel7.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));
        jPanel7.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 50, -1));

        jLabel54.setText("Menopausia");
        jPanel7.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 20));
        jPanel7.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 50, -1));

        jLabel55.setText("Fórmula menstrual");
        jPanel7.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, 20));
        jPanel7.add(txtFormulaMenstrual, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 140, -1));

        jLabel56.setText("F.U.M");
        jPanel7.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 20));
        jPanel7.add(txtFUM, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 180, -1));

        jLabel57.setText("F.U.Citología");
        jPanel7.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, 20));
        jPanel7.add(txtCitologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 160, -1));

        jLabel59.setText("de Frecuencia");
        jPanel7.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 20));

        jLabel60.setText("de Duracion");
        jPanel7.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, 20));

        jLabel61.setText("de Cantidad");
        jPanel7.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, 20));

        cmbFrecuencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Amenorrea", "Polimenorrea", "Oligomenorrea" }));
        jPanel7.add(cmbFrecuencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 80, -1));

        cmbDuracion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Menometrorragia" }));
        jPanel7.add(cmbDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 80, -1));

        cmbCantidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Hipermenorrea", "Hipomenorrea", "" }));
        jPanel7.add(cmbCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 80, -1));

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel58.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alteraciones de la mestruación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel7.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 470, 50));

        jLabel62.setText("Inicio vida sexual");
        jPanel7.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 20));
        jPanel7.add(spnVidaSexual, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 70, -1));

        jLabel63.setText("No. Parejas");
        jPanel7.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, 20));
        jPanel7.add(spnNoParejas, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 80, -1));
        jPanel7.add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 420, -1));

        cmbInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aqui se pone Date Chooser" }));
        jPanel7.add(cmbInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 160, -1));

        cmbSuspencion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aqui va un datechooser" }));
        jPanel7.add(cmbSuspencion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 140, -1));

        jLabel67.setText("Suspención");
        jPanel7.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, 20));

        jLabel66.setText("Inicio");
        jPanel7.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 20));

        jLabel65.setText("Tipo");
        jPanel7.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 20));

        jLabel64.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Anticoncepcion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel7.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 470, 80));

        jLabel68.setText("Observaciones");
        jPanel7.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane6.setViewportView(jTextArea5);

        jPanel7.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 470, 250));

        jLabel69.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESUMEN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel7.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 400, 500));

        jTabbedPane2.addTab("Ginecologicos", jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel70.setText("F.P.P");
        jPanel8.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

        cmbFPP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aqui va un date chooser" }));
        jPanel8.add(cmbFPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 150, -1));

        jLabel72.setText("G");
        jPanel8.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 20));
        jPanel8.add(spnG, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 90, -1));
        jPanel8.add(spnA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 90, -1));
        jPanel8.add(spnP, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 90, -1));
        jPanel8.add(spnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 100, -1));
        jPanel8.add(spnNacidosVivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 60, -1));
        jPanel8.add(spnNacidosMuertos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 60, -1));
        jPanel8.add(spnViven, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 70, -1));
        jPanel8.add(spnMuertoPrimeraSem, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 60, -1));
        jPanel8.add(spnMuertoDesPrimeraSem, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 70, -1));

        jLabel81.setText("Muerto despues 1ra sem.");
        jPanel8.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, 20));

        jLabel80.setText("Muerto - 1ra sem.");
        jPanel8.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, 20));

        jLabel79.setText("Viven");
        jPanel8.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, 20));

        jLabel78.setText("Nacidos muertos");
        jPanel8.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, 20));

        jLabel77.setText("Nacidos vivos");
        jPanel8.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, 20));

        jLabel76.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel8.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 450, 70));

        jLabel75.setText("C");
        jPanel8.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, 20));

        jLabel73.setText("A");
        jPanel8.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, 20));

        jLabel74.setText("P");
        jPanel8.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, 20));

        jLabel71.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel8.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 470, 120));

        jCheckBox2.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("Intergenesia");
        jPanel8.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jCheckBox3.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setText("Atencion Prenatal");
        jPanel8.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jCheckBox4.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox4.setText("Parto Prematuro");
        jPanel8.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        jCheckBox5.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox5.setText("Malformaciones");
        jPanel8.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        jCheckBox6.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox6.setText("Isoinmunizacion");
        jPanel8.add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        jLabel82.setText("No. de Consultas");
        jPanel8.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, 20));
        jPanel8.add(jSpinner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 210, 80, -1));

        jLabel83.setText("Medicación Gestacional");
        jPanel8.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 20));
        jPanel8.add(txtMediacionGestional, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 240, 330, -1));

        jLabel84.setText("Examenes Complementarios");
        jPanel8.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, 20));
        jPanel8.add(txtExamenesComplementarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 330, -1));

        jLabel85.setText("Observaciones");
        jPanel8.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jScrollPane7.setViewportView(jTextArea6);

        jPanel8.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 470, 180));

        jLabel86.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESUMEN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel8.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 390, 490));

        jTabbedPane2.addTab("Obstetricos", jPanel8);

        jPanel3.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 530));

        jTabbedPane1.addTab("Antecedentes", jPanel3);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane3.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAreaAbdomen.setColumns(20);
        txtAreaAbdomen.setRows(5);
        jScrollPane8.setViewportView(txtAreaAbdomen);

        jPanel10.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 460, 450));

        jLabel87.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Abdomen", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel10.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, 490));

        jLabel88.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESUMEN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel10.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 340, 490));

        jTabbedPane3.addTab("Abdomen", jPanel10);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel89.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cabeza", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel11.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 490));

        jTextArea7.setColumns(20);
        jTextArea7.setRows(5);
        txtAreaCabeza.setViewportView(jTextArea7);

        jPanel11.add(txtAreaCabeza, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 420, 450));

        jLabel90.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel90.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESUMEN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel11.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 350, 490));

        jTabbedPane3.addTab("Cabeza", jPanel11);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel91.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cuello", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel12.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 490));

        jLabel92.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel92.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESUMEN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel12.add(jLabel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 350, 490));

        jTextArea8.setColumns(20);
        jTextArea8.setRows(5);
        txtAreaCuello.setViewportView(jTextArea8);

        jPanel12.add(txtAreaCuello, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 420, 450));

        jTabbedPane3.addTab("Cuello", jPanel12);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel93.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel93.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESUMEN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel13.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 350, 490));

        txtAreaColumnaVertebral.setColumns(20);
        txtAreaColumnaVertebral.setRows(5);
        txtAreaCuello1.setViewportView(txtAreaColumnaVertebral);

        jPanel13.add(txtAreaCuello1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 420, 450));

        jLabel94.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Columna Vertebral", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel13.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 490));

        jTabbedPane3.addTab("Columna Vertebral", jPanel13);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel95.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel95.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESUMEN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel14.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 350, 490));

        txtAreaExploracionGinegologica.setColumns(20);
        txtAreaExploracionGinegologica.setRows(5);
        txtAreaCuello2.setViewportView(txtAreaExploracionGinegologica);

        jPanel14.add(txtAreaCuello2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 420, 450));

        jLabel96.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Exploracion Ginecologica", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel14.add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 490));

        jTabbedPane3.addTab("Exploracion Ginecologica", jPanel14);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel97.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel97.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESUMEN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel15.add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 350, 490));

        txtAreaExploracionNeurologica.setColumns(20);
        txtAreaExploracionNeurologica.setRows(5);
        txtAreaCuello3.setViewportView(txtAreaExploracionNeurologica);

        jPanel15.add(txtAreaCuello3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 420, 450));

        jLabel98.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Exploracion Neurologica", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel15.add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 490));

        jTabbedPane3.addTab("Exploracion Neurologica", jPanel15);

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel99.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel99.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESUMEN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel16.add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 350, 490));

        txtAreaExtremidades.setColumns(20);
        txtAreaExtremidades.setRows(5);
        txtAreaCuello4.setViewportView(txtAreaExtremidades);

        jPanel16.add(txtAreaCuello4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 420, 450));

        jLabel100.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Extremidades", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel16.add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 490));

        jTabbedPane3.addTab("Extremidades", jPanel16);

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel101.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel101.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESUMEN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel17.add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 350, 490));

        txtAreaGenitales.setColumns(20);
        txtAreaGenitales.setRows(5);
        txtAreaCuello5.setViewportView(txtAreaGenitales);

        jPanel17.add(txtAreaCuello5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 420, 450));

        jLabel102.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Genitales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel17.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 490));

        jTabbedPane3.addTab("Genitales", jPanel17);

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel103.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel103.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESUMEN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel18.add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 350, 490));

        txtAreaHabitusExterior.setColumns(20);
        txtAreaHabitusExterior.setRows(5);
        txtAreaCuello6.setViewportView(txtAreaHabitusExterior);

        jPanel18.add(txtAreaCuello6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 420, 450));

        jLabel104.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Habitus Exterior", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel18.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 490));

        jTabbedPane3.addTab("Habitus Exterior", jPanel18);

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel105.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel105.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESUMEN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel19.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 350, 490));

        txtAreaTorax.setColumns(20);
        txtAreaTorax.setRows(5);
        txtAreaCuello7.setViewportView(txtAreaTorax);

        jPanel19.add(txtAreaCuello7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 420, 450));

        jLabel106.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Torax", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel19.add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 490));

        jTabbedPane3.addTab("Torax", jPanel19);

        jPanel9.add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 520));

        jTabbedPane1.addTab("Exploracion Fisica", jPanel9);

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane4.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel107.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cardiovascular", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel21.add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 490));

        jLabel108.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel108.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESUMEN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel21.add(jLabel108, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 350, 490));

        jTextArea9.setColumns(20);
        jTextArea9.setRows(5);
        txtAreaCardiovascular.setViewportView(jTextArea9);

        jPanel21.add(txtAreaCardiovascular, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 420, 450));

        jTabbedPane4.addTab("Cardiovascular", jPanel21);

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel109.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Digestivo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel22.add(jLabel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 490));

        jLabel110.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel110.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESUMEN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel22.add(jLabel110, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 350, 490));

        jTextArea10.setColumns(20);
        jTextArea10.setRows(5);
        txtAreaDigestivo.setViewportView(jTextArea10);

        jPanel22.add(txtAreaDigestivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 420, 450));

        jTabbedPane4.addTab("Digestivo", jPanel22);

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel111.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endocrino", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel23.add(jLabel111, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 490));

        jLabel112.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel112.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESUMEN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel23.add(jLabel112, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 350, 490));

        jTextArea11.setColumns(20);
        jTextArea11.setRows(5);
        txtAreaEndocrino.setViewportView(jTextArea11);

        jPanel23.add(txtAreaEndocrino, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 420, 450));

        jTabbedPane4.addTab("Endocrino", jPanel23);

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel113.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hemolinfatico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel24.add(jLabel113, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 490));

        jLabel114.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel114.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESUMEN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel24.add(jLabel114, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 350, 490));

        jTextArea12.setColumns(20);
        jTextArea12.setRows(5);
        txtAreaHemolinfatico.setViewportView(jTextArea12);

        jPanel24.add(txtAreaHemolinfatico, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 420, 450));

        jTabbedPane4.addTab("Hemolinfatico", jPanel24);

        jPanel25.setBackground(new java.awt.Color(255, 255, 255));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel115.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Musculo - Esqueletico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel25.add(jLabel115, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 490));

        jLabel116.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel116.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESUMEN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel25.add(jLabel116, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 350, 490));

        jTextArea13.setColumns(20);
        jTextArea13.setRows(5);
        txtAreaMusculo.setViewportView(jTextArea13);

        jPanel25.add(txtAreaMusculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 420, 450));

        jTabbedPane4.addTab("Musculo - Esqueletico", jPanel25);

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel117.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Piel y Anexos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel26.add(jLabel117, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 490));

        jLabel118.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel118.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESUMEN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel26.add(jLabel118, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 350, 490));

        jTextArea14.setColumns(20);
        jTextArea14.setRows(5);
        txtAreaPiel.setViewportView(jTextArea14);

        jPanel26.add(txtAreaPiel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 420, 450));

        jTabbedPane4.addTab("Piel y Anexos", jPanel26);

        jPanel27.setBackground(new java.awt.Color(255, 255, 255));
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel119.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reproductor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel27.add(jLabel119, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 490));

        jLabel120.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel120.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESUMEN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel27.add(jLabel120, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 350, 490));

        jTextArea15.setColumns(20);
        jTextArea15.setRows(5);
        txtAreaReproductor.setViewportView(jTextArea15);

        jPanel27.add(txtAreaReproductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 420, 450));

        jTabbedPane4.addTab("Reproductor", jPanel27);

        jPanel28.setBackground(new java.awt.Color(255, 255, 255));
        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel121.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Respiratorio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel28.add(jLabel121, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 490));

        jLabel122.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel122.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESUMEN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel28.add(jLabel122, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 350, 490));

        jTextArea16.setColumns(20);
        jTextArea16.setRows(5);
        txtAreaRespiratorio.setViewportView(jTextArea16);

        jPanel28.add(txtAreaRespiratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 420, 450));

        jTabbedPane4.addTab("Respiratorio", jPanel28);

        jPanel29.setBackground(new java.awt.Color(255, 255, 255));
        jPanel29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel123.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sistema Nervioso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel29.add(jLabel123, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 490));

        jLabel124.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel124.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESUMEN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel29.add(jLabel124, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 350, 490));

        jTextArea17.setColumns(20);
        jTextArea17.setRows(5);
        txtAreaSistemaNervioso.setViewportView(jTextArea17);

        jPanel29.add(txtAreaSistemaNervioso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 420, 450));

        jTabbedPane4.addTab("Sistema Nervioso", jPanel29);

        jPanel30.setBackground(new java.awt.Color(255, 255, 255));
        jPanel30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel125.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sistemas Generales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel30.add(jLabel125, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 490));

        jLabel126.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel126.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESUMEN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel30.add(jLabel126, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 350, 490));

        jTextArea18.setColumns(20);
        jTextArea18.setRows(5);
        txtAreaSistemasGenerales.setViewportView(jTextArea18);

        jPanel30.add(txtAreaSistemasGenerales, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 420, 450));

        jTabbedPane4.addTab("Sistemas Generales", jPanel30);

        jPanel31.setBackground(new java.awt.Color(255, 255, 255));
        jPanel31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel127.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cuello", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel31.add(jLabel127, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 490));

        jLabel128.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel128.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESUMEN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel31.add(jLabel128, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 350, 490));

        jTextArea19.setColumns(20);
        jTextArea19.setRows(5);
        txtAreaCuello8.setViewportView(jTextArea19);

        jPanel31.add(txtAreaCuello8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 420, 450));

        jTabbedPane4.addTab("Urinario", jPanel31);

        jPanel20.add(jTabbedPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 520));

        jTabbedPane1.addTab("Interrogatorio", jPanel20);

        jPanel32.setBackground(new java.awt.Color(255, 255, 255));
        jPanel32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre del Médico", "Fecha"
            }
        ));
        jScrollPane9.setViewportView(jTable2);

        jPanel32.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 490, 390));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Busqueda_32.png"))); // NOI18N
        jButton1.setText("Ver Detalles");
        jPanel32.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 140, 50));

        txtAreaTratamiento.setColumns(20);
        txtAreaTratamiento.setRows(5);
        txtAreaDiagnostico1.setViewportView(txtAreaTratamiento);

        jPanel32.add(txtAreaDiagnostico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 390, 70));

        jTextArea22.setColumns(20);
        jTextArea22.setRows(5);
        txtAreaDiagnostico.setViewportView(jTextArea22);

        jPanel32.add(txtAreaDiagnostico, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 390, 70));

        jTextArea20.setColumns(20);
        jTextArea20.setRows(5);
        txtAreaSintomas.setViewportView(jTextArea20);

        jPanel32.add(txtAreaSintomas, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 390, 70));

        jLabel133.setText("Tratamiento");
        jPanel32.add(jLabel133, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, -1, 20));

        jLabel131.setText("Síntomas");
        jPanel32.add(jLabel131, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, -1, 20));

        jLabel132.setText("Motivo de la Consulta");
        jPanel32.add(jLabel132, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, -1, 20));

        jLabel129.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LISTADO DE CONSULTAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel32.add(jLabel129, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 530, 500));

        jLabel130.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESUMEN DE LA CONSULTA SELECCIONADA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel32.add(jLabel130, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 430, 500));

        jTextArea21.setColumns(20);
        jTextArea21.setRows(5);
        txtAreaMotivoConsulta.setViewportView(jTextArea21);

        jPanel32.add(txtAreaMotivoConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 390, 70));

        jLabel134.setText("Diagnóstico");
        jPanel32.add(jLabel134, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, -1, 20));

        jTabbedPane1.addTab("Consultas", jPanel32);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, 550));

        lblGuardarExpediente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGuardarExpediente.setForeground(new java.awt.Color(255, 255, 255));
        lblGuardarExpediente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar_32.png"))); // NOI18N
        lblGuardarExpediente.setText("Guardar Expediente");
        lblGuardarExpediente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblGuardarExpediente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblGuardarExpediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lblEliminarExpediente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEliminarExpediente.setForeground(new java.awt.Color(255, 255, 255));
        lblEliminarExpediente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CancelarCita_32.png"))); // NOI18N
        lblEliminarExpediente.setText("Eliminar Expediente");
        lblEliminarExpediente.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblEliminarExpediente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEliminarExpediente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblEliminarExpediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu Azul.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblNuevaConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNuevaConsultaMouseClicked
        new Consulta().setVisible(true);
    }//GEN-LAST:event_lblNuevaConsultaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Expediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Expediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Expediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Expediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Expediente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkAnestesia;
    private javax.swing.JCheckBox checkApnea;
    private javax.swing.JCheckBox checkCianosis;
    private javax.swing.JCheckBox checkConvulsiones;
    private javax.swing.JCheckBox checkHemorragias;
    private javax.swing.JCheckBox checkIctericia;
    private javax.swing.JComboBox<String> cmbCantidad;
    private javax.swing.JComboBox<String> cmbDuracion;
    private javax.swing.JComboBox<String> cmbFPP;
    private javax.swing.JComboBox<String> cmbFrecuencia;
    private javax.swing.JComboBox<String> cmbInicio;
    private javax.swing.JComboBox cmbMedico;
    private javax.swing.JComboBox cmbSexo;
    private javax.swing.JComboBox<String> cmbSuspencion;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea10;
    private javax.swing.JTextArea jTextArea11;
    private javax.swing.JTextArea jTextArea12;
    private javax.swing.JTextArea jTextArea13;
    private javax.swing.JTextArea jTextArea14;
    private javax.swing.JTextArea jTextArea15;
    private javax.swing.JTextArea jTextArea16;
    private javax.swing.JTextArea jTextArea17;
    private javax.swing.JTextArea jTextArea18;
    private javax.swing.JTextArea jTextArea19;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea20;
    private javax.swing.JTextArea jTextArea21;
    private javax.swing.JTextArea jTextArea22;
    private javax.swing.JTextArea jTextArea23;
    private javax.swing.JTextArea jTextArea24;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    private javax.swing.JLabel lblEliminarExpediente;
    private javax.swing.JLabel lblGuardarExpediente;
    private javax.swing.JLabel lblNuevaConsulta;
    private javax.swing.JRadioButton rdbtnCesarea;
    private javax.swing.JRadioButton rdbtnParto;
    private javax.swing.JSpinner spnA;
    private javax.swing.JSpinner spnAbdominal;
    private javax.swing.JSpinner spnApgar;
    private javax.swing.JSpinner spnBallard;
    private javax.swing.JSpinner spnC;
    private javax.swing.JSpinner spnCefalico;
    private javax.swing.JSpinner spnEdadGestacional;
    private javax.swing.JSpinner spnG;
    private javax.swing.JSpinner spnMuertoDesPrimeraSem;
    private javax.swing.JSpinner spnMuertoPrimeraSem;
    private javax.swing.JSpinner spnNacidosMuertos;
    private javax.swing.JSpinner spnNacidosVivos;
    private javax.swing.JSpinner spnNoGestacion;
    private javax.swing.JSpinner spnNoParejas;
    private javax.swing.JSpinner spnP;
    private javax.swing.JSpinner spnSilverman;
    private javax.swing.JSpinner spnToracico;
    private javax.swing.JSpinner spnVidaSexual;
    private javax.swing.JSpinner spnViven;
    private javax.swing.JTextField txtAnestesia;
    private javax.swing.JTextField txtApeMat;
    private javax.swing.JTextField txtApePat;
    private javax.swing.JTextArea txtAreaAbdomen;
    private javax.swing.JScrollPane txtAreaCabeza;
    private javax.swing.JScrollPane txtAreaCardiovascular;
    private javax.swing.JTextArea txtAreaColumnaVertebral;
    private javax.swing.JScrollPane txtAreaComplicaciones;
    private javax.swing.JScrollPane txtAreaCuello;
    private javax.swing.JScrollPane txtAreaCuello1;
    private javax.swing.JScrollPane txtAreaCuello2;
    private javax.swing.JScrollPane txtAreaCuello3;
    private javax.swing.JScrollPane txtAreaCuello4;
    private javax.swing.JScrollPane txtAreaCuello5;
    private javax.swing.JScrollPane txtAreaCuello6;
    private javax.swing.JScrollPane txtAreaCuello7;
    private javax.swing.JScrollPane txtAreaCuello8;
    private javax.swing.JScrollPane txtAreaDiagnostico;
    private javax.swing.JScrollPane txtAreaDiagnostico1;
    private javax.swing.JScrollPane txtAreaDigestivo;
    private javax.swing.JScrollPane txtAreaEndocrino;
    private javax.swing.JTextArea txtAreaExploracionGinegologica;
    private javax.swing.JTextArea txtAreaExploracionNeurologica;
    private javax.swing.JTextArea txtAreaExtremidades;
    private javax.swing.JTextArea txtAreaGenitales;
    private javax.swing.JTextArea txtAreaHabitusExterior;
    private javax.swing.JScrollPane txtAreaHemolinfatico;
    private javax.swing.JScrollPane txtAreaMotivoConsulta;
    private javax.swing.JScrollPane txtAreaMusculo;
    private javax.swing.JScrollPane txtAreaNoPAtologicos;
    private javax.swing.JScrollPane txtAreaPatologicos;
    private javax.swing.JScrollPane txtAreaPiel;
    private javax.swing.JScrollPane txtAreaReproductor;
    private javax.swing.JScrollPane txtAreaRespiratorio;
    private javax.swing.JScrollPane txtAreaSintomas;
    private javax.swing.JScrollPane txtAreaSistemaNervioso;
    private javax.swing.JScrollPane txtAreaSistemasGenerales;
    private javax.swing.JTextArea txtAreaTorax;
    private javax.swing.JTextArea txtAreaTratamiento;
    private javax.swing.JTextField txtCitologia;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtCodigoPostal;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDerechohabiente;
    private javax.swing.JTextArea txtDomicilio;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEscolaridad;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtEstadoCivil;
    private javax.swing.JTextField txtExamenesComplementarios;
    private javax.swing.JTextField txtFUM;
    private javax.swing.JTextField txtFechaNac;
    private javax.swing.JTextField txtFormulaMenstrual;
    private javax.swing.JTextField txtLugarNac1;
    private javax.swing.JTextField txtMediacionGestional;
    private javax.swing.JTextField txtNExpediente;
    private javax.swing.JTextField txtNombreMadre;
    private javax.swing.JTextField txtNombrePadre;
    private javax.swing.JTextField txtNombrePareja;
    private javax.swing.JTextField txtOcupacion;
    private javax.swing.JTextField txtPNombre;
    private javax.swing.JTextField txtPesoAlNacer;
    private javax.swing.JTextField txtProcedencia;
    private javax.swing.JTextField txtRFC;
    private javax.swing.JTextField txtSNombre;
    private javax.swing.JTextField txtSitioParto;
    private javax.swing.JTextField txtTalla;
    private javax.swing.JTextField txtTelDom;
    private javax.swing.JTextField txtTelOfi;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
